### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by freeman-lab** [freeman-lab/ppm#4]
The command-line interface tool we're using `click` has a great set of utilities for unit testing.

http://click.pocoo.org/5/testing/

We just need to add some tests with them!

cc @ericdill

**Comment by ericdill** [comment]
Working on it in #5 !

Question for you... I ripped out some of the functionality in `pim.commands.init:init` so that I could use this library programmatically instead of on the command line.  Is this something that you have any interest in for this library?

**Comment by freeman-lab** [comment]
Awesome, going through that PR now! I saw that refactoring, it definitely seems useful it nothing else for code maintenance and testing. I guess I was only imagining a CLI at first, but programmatic use could be cool too! So I'd guess I'd say, let's not prioritize it while fleshing out the core command list, but definitely worth doing things now in a way that will make it easy later.
